[default]

[openai_defaults]
api_key = "@format {env[API_KEY]}"
api_base = "@format {env[API_ENDPOINT]}"
api_version = "2025-01-01-preview"

[project_defaults]
api_base = "@format {env[FOUNDRY_PROJECT_ENDPOINT]}"
cloud_evaluation_deployment_name = "@format {env[FOUNDRY_PROJECT_EVALUATION_DEPLOYMENT_NAME]}"


[models.azure_openai_chat.gpt5]
api_key = "@jinja {{ env['GPT5_API_KEY'] or this.openai_defaults.api_key }}"
model = "gpt-5-chat"
api_base = "@jinja {{ env['GPT5_ENDPOINT'] or this.openai_defaults.api_base }}"
deployment_name = "gpt-5-chat"
api_version = "@jinja {{ env['API_VERSION'] or this.openai_defaults.api_version }}"
model_supports_json = true

[models.azure_openai_chat.gpt4]
api_key = "@jinja {{ env['GPT4_API_KEY'] or this.openai_defaults.api_key }}"
model = "gpt-4.1-mini"
api_base = "@jinja {{ env['GPT4_ENDPOINT'] or this.openai_defaults.api_base }}"
deployment_name = "gpt-4.1-mini"
api_version = "@jinja {{ env['API_VERSION'] or this.openai_defaults.api_version }}"
model_supports_json = true

[models.azure_openai_embedding.large]
api_key = "@format {this.openai_defaults.api_key }"
model = "text-embedding-3-large"
api_base = "@format {this.openai_defaults.api_base }"
deployment_name = "text-embedding-3-large"
api_version = "2023-05-15"

[evaluations]

[evaluations.gpt5]
path = "sample-gpt5/output"
model = "gpt5"

[evaluations.gpt4]
path = "sample-gpt4/output"
model = "gpt4"