[project]
name = "graph-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastmcp>=2.12.5",
    "graphrag>=2.7.0",
]

[dependency-groups]
dev = [
    "debugpy>=1.8.0",
]